### PR TITLE
Return raw data instead of CounterfactualData

### LINKED ISSUE #10: Update the functionality to return raw data
# Changes to be made:

### Synthetic:

- [x] Cast X to float32
- [x] Update comments
- [x] Update tests

### Tabular:

- [x] Implement `undersample`
- [x] Update comments
- [x] Update tests
- [x] Cast X to float32 where needed

### Vision:

- [x] Implement `undersample`
- [x] Update comments
- [x] Update tests
- [x] Cast X to float32 where needed

#### Note
This issue is added retroactively to document what I made in #9.

### PR DESCRIPTION
**Pull request by kmariuszk**
# Summary

This PR implements the most crucial part of the `TaijaData.jl` functionality. There's still a few decision to be made regarding the translation layer between `TaijaData.jl` and `CounterfactualExplanations.jl` but it's going to be resolved in another PR since this one is already big enough. 

### Synthetic:

- [x] Cast X to float32
- [x] Update comments
- [x] Update tests

### Tabular:

- [x] Implement `undersample`
- [x] Update comments
- [x] Update tests
- [x] Cast X to float32 where needed

### Vision:

- [x] Implement `undersample`
- [x] Update comments
- [x] Update tests
- [x] Cast X to float32 where needed

Closes #10.

### CODE REVIEW

**Comment by kmariuszk** [comment]
Casting issue has been solved by moving it to `CounterfactualData` constructor in `CounterfactualExplanations.jl` package.

Link to PR: https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/pull/359

**Comment by kmariuszk** [comment]
Hey @pat-alt, I've a question about the type of the data we want to return as a base, currently I simply changed `return CounterfactualData` to `return (X, y)` tuple and got the following types:

```
cifar_10----Tuple{Matrix{Float32}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
adult----Tuple{Matrix{Float64}, Vector{Int64}}
blobs----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
moons----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
gmsc----Tuple{Matrix{Float64}, Vector{Int64}}
fashion_mnist----Tuple{Matrix{Float32}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
overlapping----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
linearly_separable----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
german_credit----Tuple{Matrix{Float64}, Vector{Int64}}
california_housing----Tuple{Matrix{Float64}, Vector{Int64}}
credit_default----Tuple{Matrix{Float64}, Vector{Int64}}
circles----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
multi_class----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
mnist----Tuple{Matrix{Float32}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
```

So, basically there are two different types of `X`'s (`Matrix` and `Tables.MatrixTable`) and two different types of `y`'s (``Vector` and CategoricalArrays.CategoricalVector`). I think it'd be cool to standardize this and always return `Tuple{Matrix, Vector}` but I don't fully understand the difference between the mentioned types. Can you share your view on that?

**Comment by pat-alt** [comment]
> Hey @pat-alt, I've a question about the type of the data we want to return as a base, currently I simply changed `return CounterfactualData` to `return (X, y)` tuple and got the following types:
> 
> ```
> cifar_10----Tuple{Matrix{Float32}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> adult----Tuple{Matrix{Float64}, Vector{Int64}}
> blobs----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> moons----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> gmsc----Tuple{Matrix{Float64}, Vector{Int64}}
> fashion_mnist----Tuple{Matrix{Float32}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> overlapping----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> linearly_separable----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> german_credit----Tuple{Matrix{Float64}, Vector{Int64}}
> california_housing----Tuple{Matrix{Float64}, Vector{Int64}}
> credit_default----Tuple{Matrix{Float64}, Vector{Int64}}
> circles----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> multi_class----Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> mnist----Tuple{Matrix{Float32}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}
> ```
> 
> So, basically there are two different types of `X`'s (`Matrix` and `Tables.MatrixTable`) and two different types of `y`'s (``Vector` and CategoricalArrays.CategoricalVector`). I think it'd be cool to standardize this and always return `Tuple{Matrix, Vector}` but I don't fully understand the difference between the mentioned types. Can you share your view on that?

I'm also in favor of raw arrays. Using tables is `MLJ` convention but it's not strictly needed anywhere

**Review by pat-alt — COMMENTED** [review]
Looks good. What's the rationale behind renaming everything to `_raw` though?

**Comment by kmariuszk** [comment]
> Looks good. What's the rationale behind renaming everything to `_raw` though?

When I started updating the functionality I thought about the translation layer (e.g., `load_blobs_CE()`) and thought I should keep a clear distinction between `raw` and `translated/processed` data but after a second thought I think the whole translation layer is unnecessary and I'm going to delete `_raw` appendix. If we eventually decide on adding a translation layer we can open another PR for that.

**Pull request merged**
